# Generated by Django 5.2.9 on 2025-12-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Ник пользователя в Telegram', max_length=255, unique=True, verbose_name='Ник')),
                ('first_name', models.CharField(help_text='Имя пользователя', max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Фамилия пользователя', max_length=255, verbose_name='Фамилия')),
                ('telegram_id', models.BigIntegerField(blank=True, help_text='ID пользователя в Telegram', null=True, unique=True, verbose_name='Telegram ID')),
                ('position', models.CharField(blank=True, help_text='Текущая должность пользователя', max_length=255, null=True, verbose_name='Должность')),
                ('is_from_rf', models.BooleanField(blank=True, help_text='Работает ли пользователь с территории РФ', null=True, verbose_name='Из РФ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'ordering': ['-created_at'],
            },
        ),
    ]
