# Generated by Django 5.2.9 on 2025-12-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, help_text='Ник пользователя в Telegram', max_length=255, null=True, verbose_name='Ник'),
        ),
    ]
