# Generated by Django 5.2.9 on 2025-12-07 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_telegramuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(help_text='Установите текущую дату для определения доступности подарков', verbose_name='Текущая дата')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройка календаря',
                'verbose_name_plural': 'Настройки календаря',
            },
        ),
        migrations.CreateModel(
            name='GiftOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text='День декабря (8-19)', verbose_name='День')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата открытия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_openings', to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Открытый подарок',
                'verbose_name_plural': 'Открытые подарки',
                'ordering': ['-opened_at'],
                'unique_together': {('user', 'day')},
            },
        ),
    ]
