# Generated by Django 5.2.9 on 2025-12-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_calendarsettings_giftopening'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='startapp_token',
            field=models.CharField(blank=True, help_text='Уникальный токен для запуска Mini App через startapp', max_length=64, null=True, unique=True, verbose_name='StartApp токен'),
        ),
    ]
