# Generated by Django 5.2.9 on 2025-12-11 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_telegramuser_startapp_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='startapp_token',
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.CharField(help_text='Использованный промокод из резерва', max_length=50, unique=True, verbose_name='Промокод')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата использования')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usages', to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Использованный промокод',
                'verbose_name_plural': 'Использованные промокоды',
                'ordering': ['-used_at'],
            },
        ),
    ]
