# Generated by Django 5.2.9 on 2025-12-18 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_telegramuser_startapp_token_promocodeusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='future_letter_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда получили письмо'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='future_letter_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда попросили написать письмо'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_waiting_future_letter',
            field=models.BooleanField(default=False, help_text='Если True — следующее сообщение пользователя будет сохранено как письмо в будущее', verbose_name='Ожидается письмо в будущее'),
        ),
        migrations.CreateModel(
            name='FutureLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст письма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('send_at', models.DateTimeField(verbose_name='Когда отправить')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда отправили')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_letters', to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Письмо в будущее',
                'verbose_name_plural': 'Письма в будущее',
                'ordering': ['-created_at'],
            },
        ),
    ]
